package com.hospital.norvic.common.constant;

import lombok.Getter;

@Getter
public enum Designation {
    GENERAL_PRACTITIONER,
    SPECIALIST,
    SURGEON,
    ANESTHESIOLOGIST,
    RADIOLOGIST,
    REGISTERED_NURSE,
    NURSE_PRACTITIONER,
    LICENSED_PRACTICAL_NURSE,
    NURSE_MANAGER,
    PSYCHOTHERAPIST,
    OCCUPATIONAL_THERAPIST,
    MEDICAL_DOCTOR,
    CHIEF_MEDICAL_OFFICER,
    CHIEF_NURSING_OFFICER,
    HOSPITAL_ADMINISTRATOR,
    PARAMEDIC,
    RADIOLOGIC_TECHNOLOGIST,
    INFECTION_CONTROL_PRACTITIONER,
    CLINICAL_RESEARCHER,
    MEDICAL_EDUCATOR,
    CLINICAL_INSTRUCTOR,
    CLEANER,
    MEDICAL_WASTE_CLEANER;

}
